{
 "title": "Sysbench & Nodes",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Worker cv55w",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  node_status\nFROM `perf1-mz8bt-worker-cv55w`\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Worker d2hdm",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  node_status\nFROM `perf1-mz8bt-worker-d2hdm`\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Worker k68rv",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  node_status\nFROM `perf1-mz8bt-worker-k68rv`\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Worker ntkp8",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  node_status\nFROM `perf1-mz8bt-worker-ntkp8`\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Worker qpwsr",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  node_status\nFROM `perf1-mz8bt-worker-qpwsr`\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  d_reads\nFROM benchmark\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  d_writes\nFROM benchmark\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Fsyncs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  d_fsyncs\nFROM benchmark\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  d_latency\nFROM benchmark\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  }
 ]
}