---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sysbench-readwrite
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-storagecluster-cephfs