apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: jobcounter
  namespace: sysbench
spec:
  selector:
    name: jobcounter
  replicas: 1
  template:
    metadata:
      labels:
        name: jobcounter
    spec:
      serviceAccountName: jobcounter
      affinity:
        nodeAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname 
                operator: In 
                values:
                - perf1-mz8bt-worker-cv55w
      containers:
      - resources:
          limits:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        name: jobcounter
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: database-user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: database-password
          - name: MYSQL_HOST
            value: 'mariadb'
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: database-name
        imagePullPolicy: IfNotPresent
        terminationMessagePolicy: File
        image: quay.io/guimou/jobcounter:0.2
      restartPolicy: Always
